---
title: "Rethinking | Notes"
author: "Lukas Feuer"
output: 
  html_notebook:
    toc: true
    toc_float: true
---

***
Personal notes for *Statistical Rethinking - 2nd Edition* by Richard McElreath

***


# 1 | The Golem of Prague 

* Because of *Overfitting*, it is almost always possible to do better than linear regression 
* Deductive falsification does not work because:
  * Usually there is not a 1:1 relationship between models and hypothesis 
  * Measurement can differ and can be debated. Therefore observers might differ in the opinion, if data is falsifying a model
* NHST is trying to falsify the null hypothesis, not the actual research hypothesis --> reverse from Karl Poppers original idea 
* The exponential family of distributions 
  * contains for example: normal, binomial, poisson distributions 
  * "loved by Nature" because they are *maximum entropy* distributions 
* Problems of the falsification approach:
  * Measurement Error: more often than not, there is great uncertainty, if the measurement, which might render a hypothesis false, is actually correct 
  * Continuous Hypothesis: usually, hypothesis are not just dichotomous. Instead of "all swans are black" usually they fall more in the range of "a certain percentage of swans is black". These Hs are much harder to falsify 
* „So if attempting to mimic falsification is not a generally useful approach to statistical methods, what are we to do? We are to model.“
* „Nothing in the real world—excepting controversial interpretations of quantum physics—is actually random. We just use randomness to describe our uncertainty in the face of incomplete knowledge.“
* „I want to convince the reader of something that appears unreasonable: multilevel regression deserves to be the default form of regression. Papers that do not use multilevel models should have to justify not using a multilevel approach.“
* „A complete scientific model contains more information than a statistical model derived from it. And this additional information contains causal implications. These implications make it possible to test alternative causal models.“
* „Causal inference requires a causal model that is separate from the statistical model. The data are not enough.“



# 2 | Small Worlds and Large Worlds

* 

```{r}
plot(cars)
```
